### ISSUE TITLE
[Request] 能帮忙添加下紫东太初及360智脑的 Icon

### ISSUE THREAD

**Issue by hezhijie0327** [lobehub/lobe-icons#27]
### 🥰 需求描述 | Feature Description

打算对这两个模型做适配，缺少相关 Icon 

### 🧐 解决方案 | Proposed Solution

 以下为两个模型的介绍：

紫东太初
https://ai-maas.wair.ac.cn/#/

360智脑
https://ai.360.com/

**Comment by canisminor1990** [comment]
@hezhijie0327 https://github.com/lobehub/lobe-icons/commit/02e68488edd77342957ea99c1b7fa2f213251aad
