### ISSUE TITLE
[Request] 帮忙增加下 CodeGeeX 模型 icon

### ISSUE THREAD

**Issue by hezhijie0327** [lobehub/lobe-icons#30]
### 🥰 需求描述 | Feature Description

For LobeChat PR: https://github.com/lobehub/lobe-chat/pull/3255

### 🧐 解决方案 | Proposed Solution

官网 SVG 图标 URL: `https://codegeex.cn/static/logo_new.272d6ea0.svg`

![image](https://codegeex.cn/static/logo_new.272d6ea0.svg) 

### 📝 补充信息 | Additional Information

Ref:
https://codegeex.cn
https://github.com/THUDM/CodeGeeX4

**Comment by canisminor1990** [comment]
@hezhijie0327 done
