### ISSUE TITLE
[Request] 帮忙增加下 Aya (Cohere) 模型 Icon

### ISSUE THREAD

**Issue by hezhijie0327** [lobehub/lobe-icons#32]
### 🥰 需求描述 | Feature Description

官网 SVG 图标：`https://cdn.sanity.io/images/rjtqmwfu/production/5bc885878e9f0f1e202b742c86f543c7fe765376-409x144.svg`
![image](https://cdn.sanity.io/images/rjtqmwfu/production/5bc885878e9f0f1e202b742c86f543c7fe765376-409x144.svg) 

### 🧐 解决方案 | Proposed Solution

ref: https://cohere.com/research/aya

**Comment by canisminor1990** [comment]
@hezhijie0327 done
