### ISSUE TITLE
[Request] 帮忙增加下 Gitee 模型供应商图标

### ISSUE THREAD

**Issue by hezhijie0327** [lobehub/lobe-icons#53]
### 🥰 需求描述 | Feature Description

ref: https://ai.gitee.com

### 🧐 解决方案 | Proposed Solution

![image](https://ai-assets.gitee.com/_next/static/media/logo-full.e6d11034.svg)

https://ai-assets.gitee.com/_next/static/media/logo-full.e6d11034.svg

### 📝 补充信息 | Additional Information

https://github.com/lobehub/lobe-chat/pull/4716

**Comment by canisminor1990** [comment]
done
